# Makefile autogenerated by Dyi on March 30, 2016
#
# Main target: all
# Sources:  src/allocate.js  src/index.js  src/prog.js  src/slots.js  src/test.js  src/xlsx.js 

.DEFAULT_GOAL := all


.PHONY: docs
docs: k-i995sd6h k-uojglfwo k-ppj9waev k-r8hnkjv5 k-4yy4vcfu k-ah0i17r1


.PHONY: c-nb2x17gp
c-nb2x17gp: lib/allocate.js lib/index.js lib/prog.js lib/slots.js lib/test.js lib/xlsx.js


.PHONY: build
build: c-nb2x17gp


.PHONY: test
test: k-eqhd3jtv k-ti22wej6


.PHONY: update
update: k-x8vjcod9


.PHONY: major
major: k-upfj4eik k-reo0s94s k-8kpinaf6


.PHONY: minor
minor: k-9tgv3g54 k-6a4gjmsm k-thn3nxfm


.PHONY: patch
patch: k-3p0nucil k-n7qls4af k-c4i42owe


.PHONY: prepare
prepare: lib




.PHONY: k-i995sd6h
k-i995sd6h:  
	./node_modules/.bin/git-hist history.md


.PHONY: k-uojglfwo
k-uojglfwo:  
	./node_modules/.bin/mustache package.json docs/readme.md | ./node_modules/.bin/stupid-replace '~USAGE~' -f docs/usage.md > readme.md


.PHONY: k-ppj9waev
k-ppj9waev:  
	cat history.md >> readme.md


.PHONY: k-r8hnkjv5
k-r8hnkjv5:  
	mkdir -p ./man/man1


.PHONY: k-4yy4vcfu
k-4yy4vcfu:  
	pandoc -s -f markdown -t man readme.md > ./man/man1/autoprog.1


.PHONY: k-ah0i17r1
k-ah0i17r1:  
	hub cm 'update docs and history.md'


.PHONY: k-cxqtfaal
k-cxqtfaal:  
	((echo '#!/usr/bin/env node') && cat ./lib/index.js) > index.js


.PHONY: k-lslyok7v
k-lslyok7v:  
	chmod +x ./index.js


.PHONY: k-ehqsquel
k-ehqsquel:  
	./index.js schedule ./fixtures/2015-2016.json -x


.PHONY: all
all: 
	make build 
	make k-cxqtfaal 
	make k-lslyok7v 
	make k-ehqsquel  


.PHONY: k-eqhd3jtv
k-eqhd3jtv:  
	make all


.PHONY: k-ti22wej6
k-ti22wej6:  
	./node_modules/.bin/mocha ./lib/test.js


.PHONY: k-x8vjcod9
k-x8vjcod9:  
	make clean && ./node_modules/.bin/babel configure.js | node


.PHONY: k-upfj4eik
k-upfj4eik:  
	make all


.PHONY: k-reo0s94s
k-reo0s94s:  
	make docs


.PHONY: k-8kpinaf6
k-8kpinaf6:  
	./node_modules/.bin/xyz -i major


.PHONY: k-9tgv3g54
k-9tgv3g54:  
	make all


.PHONY: k-6a4gjmsm
k-6a4gjmsm:  
	make docs


.PHONY: k-thn3nxfm
k-thn3nxfm:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-3p0nucil
k-3p0nucil:  
	make all


.PHONY: k-n7qls4af
k-n7qls4af:  
	make docs


.PHONY: k-c4i42owe
k-c4i42owe:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  
	rm -f lib/allocate.js
	rm -f lib/index.js
	rm -f lib/prog.js
	rm -f lib/slots.js
	rm -f lib/test.js
	rm -f lib/xlsx.js




lib/allocate.js: src/allocate.js 
	./node_modules/.bin/babel src/allocate.js -o ./lib/allocate.js

lib/index.js: src/index.js 
	./node_modules/.bin/babel src/index.js -o ./lib/index.js

lib/prog.js: src/prog.js 
	./node_modules/.bin/babel src/prog.js -o ./lib/prog.js

lib/slots.js: src/slots.js 
	./node_modules/.bin/babel src/slots.js -o ./lib/slots.js

lib/test.js: src/test.js 
	./node_modules/.bin/babel src/test.js -o ./lib/test.js

lib/xlsx.js: src/xlsx.js 
	./node_modules/.bin/babel src/xlsx.js -o ./lib/xlsx.js

lib: 
	mkdir -p lib

