# Makefile autogenerated by Dyi on September 11, 2017
#
# Main target: all
# Sources:  src/allocate.js  src/index.js  src/prog.js  src/slots.js  src/test.js  src/xlsx.js 

.DEFAULT_GOAL := all


.PHONY: docs
docs: k-c83oqh3a k-g86ed6ni k-taqcr4so k-77cmylil k-w8ccf6xk k-cow7gkco


.PHONY: c-but6rlu1
c-but6rlu1: lib/allocate.js lib/index.js lib/prog.js lib/slots.js lib/test.js lib/xlsx.js


.PHONY: build
build: c-but6rlu1


.PHONY: test
test: k-w3ewjx0h k-dbi9v0ob


.PHONY: update
update: k-w8f5ynfp


.PHONY: major
major: k-oisd7wj3 k-4pnclbmf k-xyip8cvo


.PHONY: minor
minor: k-2u0sull6 k-9vaj91qd k-tb6a5fg7


.PHONY: patch
patch: k-kqld87mt k-40xpiv90 k-mr3wwikg


.PHONY: prepare
prepare: lib




.PHONY: k-c83oqh3a
k-c83oqh3a:  
	./node_modules/.bin/git-hist history.md


.PHONY: k-g86ed6ni
k-g86ed6ni:  
	./node_modules/.bin/mustache package.json docs/readme.md | ./node_modules/.bin/stupid-replace '~USAGE~' -f docs/usage.md > readme.md


.PHONY: k-taqcr4so
k-taqcr4so:  
	cat history.md >> readme.md


.PHONY: k-77cmylil
k-77cmylil:  
	mkdir -p ./man/man1


.PHONY: k-w8ccf6xk
k-w8ccf6xk:  
	pandoc -s -f markdown -t man readme.md > ./man/man1/autoprog.1


.PHONY: k-cow7gkco
k-cow7gkco:  
	hub cm 'update docs and history.md'


.PHONY: k-64c0lgup
k-64c0lgup:  
	((echo '#!/usr/bin/env node') && cat ./lib/index.js) > index.js


.PHONY: k-egmsk4ja
k-egmsk4ja:  
	chmod +x ./index.js


.PHONY: all
all: 
	make build 
	make k-64c0lgup 
	make k-egmsk4ja  


.PHONY: k-w3ewjx0h
k-w3ewjx0h:  
	make all


.PHONY: k-dbi9v0ob
k-dbi9v0ob:  
	./node_modules/.bin/mocha -b -t 5000 ./lib/test.js


.PHONY: k-w8f5ynfp
k-w8f5ynfp:  
	make clean && ./node_modules/.bin/babel configure.js | node


.PHONY: k-oisd7wj3
k-oisd7wj3:  
	make all


.PHONY: k-4pnclbmf
k-4pnclbmf:  
	make docs


.PHONY: k-xyip8cvo
k-xyip8cvo:  
	./node_modules/.bin/xyz -i major


.PHONY: k-2u0sull6
k-2u0sull6:  
	make all


.PHONY: k-9vaj91qd
k-9vaj91qd:  
	make docs


.PHONY: k-tb6a5fg7
k-tb6a5fg7:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-kqld87mt
k-kqld87mt:  
	make all


.PHONY: k-40xpiv90
k-40xpiv90:  
	make docs


.PHONY: k-mr3wwikg
k-mr3wwikg:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  
	rm -f lib/allocate.js
	rm -f lib/index.js
	rm -f lib/prog.js
	rm -f lib/slots.js
	rm -f lib/test.js
	rm -f lib/xlsx.js




lib/allocate.js: src/allocate.js 
	./node_modules/.bin/babel src/allocate.js -o ./lib/allocate.js

lib/index.js: src/index.js 
	./node_modules/.bin/babel src/index.js -o ./lib/index.js

lib/prog.js: src/prog.js 
	./node_modules/.bin/babel src/prog.js -o ./lib/prog.js

lib/slots.js: src/slots.js 
	./node_modules/.bin/babel src/slots.js -o ./lib/slots.js

lib/test.js: src/test.js 
	./node_modules/.bin/babel src/test.js -o ./lib/test.js

lib/xlsx.js: src/xlsx.js 
	./node_modules/.bin/babel src/xlsx.js -o ./lib/xlsx.js

lib: 
	mkdir -p lib

