# Makefile autogenerated by Dyi on March 31, 2016
#
# Main target: all
# Sources:  src/allocate.js  src/index.js  src/prog.js  src/slots.js  src/test.js  src/xlsx.js 

.DEFAULT_GOAL := all


.PHONY: docs
docs: k-90cm2hjn k-ld8w2w2s k-xomp5pam k-g5f8wdod k-iakn4r99 k-ca6f5som


.PHONY: c-n6tay3t8
c-n6tay3t8: lib/allocate.js lib/index.js lib/prog.js lib/slots.js lib/test.js lib/xlsx.js


.PHONY: build
build: c-n6tay3t8


.PHONY: test
test: k-ndjbwjkn k-m2sbg4sv


.PHONY: update
update: k-k8h919uf


.PHONY: major
major: k-va75q0co k-qdg14x1k k-s02rn47d


.PHONY: minor
minor: k-coi9lmm7 k-qcblbj8q k-5522j2al


.PHONY: patch
patch: k-4c2fmjwh k-3sbd5fax k-5mi3pb7i


.PHONY: prepare
prepare: lib




.PHONY: k-90cm2hjn
k-90cm2hjn:  
	./node_modules/.bin/git-hist history.md


.PHONY: k-ld8w2w2s
k-ld8w2w2s:  
	./node_modules/.bin/mustache package.json docs/readme.md | ./node_modules/.bin/stupid-replace '~USAGE~' -f docs/usage.md > readme.md


.PHONY: k-xomp5pam
k-xomp5pam:  
	cat history.md >> readme.md


.PHONY: k-g5f8wdod
k-g5f8wdod:  
	mkdir -p ./man/man1


.PHONY: k-iakn4r99
k-iakn4r99:  
	pandoc -s -f markdown -t man readme.md > ./man/man1/autoprog.1


.PHONY: k-ca6f5som
k-ca6f5som:  
	hub cm 'update docs and history.md'


.PHONY: k-wn9bq5uh
k-wn9bq5uh:  
	((echo '#!/usr/bin/env node') && cat ./lib/index.js) > index.js


.PHONY: k-3hpr102o
k-3hpr102o:  
	chmod +x ./index.js


.PHONY: all
all: 
	make build 
	make k-wn9bq5uh 
	make k-3hpr102o  


.PHONY: k-ndjbwjkn
k-ndjbwjkn:  
	make all


.PHONY: k-m2sbg4sv
k-m2sbg4sv:  
	./node_modules/.bin/mocha ./lib/test.js


.PHONY: k-k8h919uf
k-k8h919uf:  
	make clean && ./node_modules/.bin/babel configure.js | node


.PHONY: k-va75q0co
k-va75q0co:  
	make all


.PHONY: k-qdg14x1k
k-qdg14x1k:  
	make docs


.PHONY: k-s02rn47d
k-s02rn47d:  
	./node_modules/.bin/xyz -i major


.PHONY: k-coi9lmm7
k-coi9lmm7:  
	make all


.PHONY: k-qcblbj8q
k-qcblbj8q:  
	make docs


.PHONY: k-5522j2al
k-5522j2al:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-4c2fmjwh
k-4c2fmjwh:  
	make all


.PHONY: k-3sbd5fax
k-3sbd5fax:  
	make docs


.PHONY: k-5mi3pb7i
k-5mi3pb7i:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  
	rm -f lib/allocate.js
	rm -f lib/index.js
	rm -f lib/prog.js
	rm -f lib/slots.js
	rm -f lib/test.js
	rm -f lib/xlsx.js




lib/allocate.js: src/allocate.js 
	./node_modules/.bin/babel src/allocate.js -o ./lib/allocate.js

lib/index.js: src/index.js 
	./node_modules/.bin/babel src/index.js -o ./lib/index.js

lib/prog.js: src/prog.js 
	./node_modules/.bin/babel src/prog.js -o ./lib/prog.js

lib/slots.js: src/slots.js 
	./node_modules/.bin/babel src/slots.js -o ./lib/slots.js

lib/test.js: src/test.js 
	./node_modules/.bin/babel src/test.js -o ./lib/test.js

lib/xlsx.js: src/xlsx.js 
	./node_modules/.bin/babel src/xlsx.js -o ./lib/xlsx.js

lib: 
	mkdir -p lib

